apiVersion: v1
kind: Service
metadata:
  name: experimental-mcp-server-duckdb
  namespace: biodiversity
spec:
  selector:
    app: experimental-duckdb-mcp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
