"""Python example: query the public data with ibis (no MCP server, no LLM).

The Python parallel to query_dbplyr.R. Users who prefer a dataframe API over raw
SQL don't need the MCP server to *read* the data: point a local DuckDB at the
public source.coop mirror (AWS us-west-2, anonymous) and let ibis compile its
deferred expressions to DuckDB SQL. Use the MCP server's STAC tools (see
query.py -> get_stac_details) to discover paths and columns; read the data here.
filter/select/order_by/aggregations/joins push down into DuckDB -- only the
final .execute() pulls rows into Python.

Install:
    pip install 'ibis-framework[duckdb]'

Run (self-checking -- exits non-zero if the query route breaks):
    python query_ibis.py
"""
import ibis

con = ibis.duckdb.connect()
con.raw_sql("INSTALL httpfs; LOAD httpfs;")

# Anonymous reads from the source.coop mirror (AWS us-west-2). The bucket name
# has dots, so URL_STYLE 'path' is required for the TLS certificate to match.
con.raw_sql(
    """
    CREATE SECRET source_coop (
      TYPE S3, KEY_ID '', SECRET '',
      ENDPOINT 's3.us-west-2.amazonaws.com', REGION 'us-west-2',
      URL_STYLE 'path', USE_SSL 'true',
      SCOPE 's3://us-west-2.opendata.source.coop'
    )"""
)

path = (
    "s3://us-west-2.opendata.source.coop/"
    "cboettig/overturemaps/2026-02-18.0/countries.parquet"
)
# EXCLUDE the GEOMETRY column: ibis's type mapper can't represent DuckDB's
# GEOMETRY type during schema inference. (The attribute columns are all we need.)
con.raw_sql(
    f"CREATE VIEW countries AS SELECT * EXCLUDE (geometry) FROM read_parquet('{path}')"
)

countries = con.table("countries")

expr = (
    countries.filter((countries.subtype == "country") & countries.is_land)
    .select("country", "name_en", "subtype")
    .order_by("name_en")
    .limit(10)
)

print("--- DuckDB SQL generated by ibis ---")
print(ibis.to_sql(expr))

df = expr.execute()
print("\n--- result ---")
print(df)

# Smoke test: the pushdown query returns exactly the 10 rows we asked for, with
# the expected columns. Fails loudly (non-zero exit) if the route breaks.
assert len(df) == 10, f"expected 10 rows, got {len(df)}"
assert list(df.columns) == ["country", "name_en", "subtype"], df.columns
assert (df["subtype"] == "country").all()
print("\nOK: ibis -> DuckDB -> S3 Parquet route works")
