# R example: query the public data with dplyr / dbplyr (no MCP server, no LLM).
#
# R users who prefer dplyr over raw SQL don't need the MCP server to *read* the
# data: point a local DuckDB at the public source.coop mirror (AWS us-west-2,
# anonymous) and dbplyr compiles your dplyr verbs to DuckDB SQL. Use the MCP
# server's STAC tools (see query.R -> get_stac_details) to discover paths and
# columns; read the data here. filter/select/arrange/summarise/joins push down
# into DuckDB -- only the final collect() pulls rows into R.
#
# Install:
#   install.packages(c("DBI", "duckdb", "dplyr", "dbplyr"))
#
# Run (self-checking -- exits non-zero if the query route breaks):
#   Rscript query_dbplyr.R

library(DBI)
library(duckdb)
library(dplyr)
library(dbplyr)

con <- dbConnect(duckdb::duckdb())
dbExecute(con, "INSTALL httpfs; LOAD httpfs;")

# Anonymous reads from the source.coop mirror (AWS us-west-2). The bucket name
# has dots, so URL_STYLE 'path' is required for the TLS certificate to match.
dbExecute(con, "
  CREATE SECRET source_coop (
    TYPE S3, KEY_ID '', SECRET '',
    ENDPOINT 's3.us-west-2.amazonaws.com', REGION 'us-west-2',
    URL_STYLE 'path', USE_SSL 'true',
    SCOPE 's3://us-west-2.opendata.source.coop'
  )")

# Register the Parquet dataset as a view, then treat it as a dplyr table.
path <- "s3://us-west-2.opendata.source.coop/cboettig/overturemaps/2026-02-18.0/countries.parquet"
dbExecute(con, sprintf(
  "CREATE VIEW countries AS SELECT * FROM read_parquet('%s')", path))

countries <- tbl(con, "countries")

q <- countries |>
  filter(subtype == "country", is_land) |>
  select(country, name_en, subtype) |>
  arrange(name_en) |>
  head(10)

cat("--- DuckDB SQL generated by dbplyr ---\n")
cat(dbplyr::sql_render(q), "\n\n")

result <- collect(q)
cat("--- result ---\n")
print(as.data.frame(result))

dbDisconnect(con, shutdown = TRUE)

# Smoke test: the pushdown query returns exactly the 10 rows we asked for,
# with the expected columns. Fails loudly (non-zero exit) if the route breaks.
stopifnot(
  nrow(result) == 10L,
  identical(names(result), c("country", "name_en", "subtype")),
  all(result$subtype == "country")
)
cat("\nOK: dplyr/dbplyr -> DuckDB -> S3 Parquet route works\n")
